# Generated by Django 5.1 on 2024-08-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='image',
            field=models.ImageField(default='', upload_to='testBadhe/badge/badges/media'),
        ),
    ]
