# Generated by Django 5.1 on 2024-08-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0008_alter_badge_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='Код пользователя')),
                ('badge_id', models.IntegerField(verbose_name='Код значка')),
            ],
        ),
    ]
