# Generated by Django 5.1.1 on 2024-09-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
