# Generated by Django 5.1 on 2024-09-13 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compmodel',
            name='children',
        ),
        migrations.RemoveField(
            model_name='compmodel',
            name='prepod',
        ),
    ]
