# Generated by Django 5.1 on 2024-09-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_news', models.CharField(default='News!', max_length=100, verbose_name='Название')),
                ('anons', models.CharField(default='', max_length=255, verbose_name='Анонс')),
                ('full_text', models.TextField(verbose_name='Статья')),
                ('dates', models.DateTimeField(verbose_name='Дата: ')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
