# Generated by Django 5.1 on 2024-08-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
